### ISSUE TITLE
Game option and email back message...?? 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#60]
Hi all, just went on to the staging of the app and it came up with this message regarding playing a game,, any ideas why? Also, the message at the bottom states that we will email them back, which we wont be doing so not sure why that is appearing either, any clarification would be great :) 

![chat screen](https://user-images.githubusercontent.com/44438071/48699485-751ffe00-ebe1-11e8-8b4b-b17336754fa3.png)

**Comment by lucymk** [comment]
Hey @joannayoungs, thanks for checking everything out and making issues! 

These are both inbuilt Crisp features, but I can disable them.

**Comment by joannayoungs** [comment]
Yes please if you can disable them that would be great @lucymk

**Comment by lucymk** [comment]
Hi @joannayoungs, I've disabled the game but can't disable the message, however I can change it to say something else. At the moment I've changed it to "Just to let you know, none of our advisors are currently online." - if you want to change it to something else (it can't be longer than that) then just let me know what 😃 otherwise, you can close the issue once you've checked it out!
